# Generated by Django 3.2.3 on 2021-05-18 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_product', '0002_productattribute_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattributevalue',
            name='attribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog_product.productattribute', verbose_name='Параметр'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog_product.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='value_boolean',
            field=models.BooleanField(null=True, verbose_name='Логический параметр'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='value_image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='value_integer',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True, verbose_name='Числовой параметр'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='value_text',
            field=models.TextField(max_length=500, null=True, verbose_name='Текстовый параметр'),
        ),
    ]
