# Generated by Django 3.2.3 on 2021-05-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_product', '0003_auto_20210518_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattributevalue',
            name='value_boolean',
            field=models.BooleanField(blank=True, null=True, verbose_name='Логический параметр'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='value_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='value_integer',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Числовой параметр'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='value_text',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Текстовый параметр'),
        ),
    ]
