# Generated by Django 3.2.3 on 2021-05-18 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_product', '0004_auto_20210518_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productattributevalue',
            old_name='value_integer',
            new_name='value_number',
        ),
    ]
