# Generated by Django 3.2.3 on 2021-05-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_product', '0006_auto_20210519_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattributevalue',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, related_name='values', to='catalog_product.Product', verbose_name='Товар'),
        ),
    ]
