# Generated by Django 3.2.3 on 2021-05-26 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_product', '0010_alter_productprice_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprice',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog_product.product', verbose_name='Товар'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='values', to='catalog_product.Product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='value',
            field=models.ManyToManyField(related_name='values', to='catalog_product.ProductAttributeValue', verbose_name='Набор характеристик'),
        ),
    ]
